export const lyrics: {
    songName: string,
    albumCover: string,
    artist: string,
    beforeMp3path: string,
    afterMp3path: string,
    beforeLyrics: { word: string, time: number }[],
    afterLyrics: string,
    extendedLyrics: { word: string, time: number }[],
}[] = [
        {
            songName: "Wait for It",
            albumCover: "https://upload.wikimedia.org/wikipedia/en/5/5b/Hamilton_cast_recording_cover.jpeg",
            artist: "Leslie Odom Jr.",
            beforeMp3path: "/waitforitbefore.mp3",
            afterMp3path: "/waitforitafter.mp3",
            beforeLyrics: [
                { word: "life", time: 1000 },
                { word: "doesn't", time: 100 },
                { word: "discriminate", time: 300 },
                { word: "NEWLINE", time: 400 },
                { word: "between", time: 600 },
                { word: "the", time: 100 },
            ],
            afterLyrics: "the sinners and the saints",
            extendedLyrics: [
                { word: "it", time: 1000 },
                { word: "takes", time: 400 },
                { word: "and", time: 100 },
                { word: "it", time: 200 },
                { word: "takes", time: 400 },
                { word: "and", time: 100 },
                { word: "it", time: 200 },
                { word: "takes", time: 600 },
            ]
        },
        {
            songName: "The Room Where It Happened",
            albumCover: "https://upload.wikimedia.org/wikipedia/en/5/5b/Hamilton_cast_recording_cover.jpeg",
            artist: "Leslie Odom Jr., Lin-Manuel Miranda",
            beforeMp3path: "/theroomwhereithappensbefore.mp3",
            afterMp3path: "/theroomwhereithappensafter.mp3",
            beforeLyrics: [
                { word: "no", time: 0 },
                { word: "one", time: 10 },
                { word: "really", time: 200 },
                { word: "knows", time: 400 },
                { word: "how", time: 400 },
                { word: "the", time: 100 },
                { word: "parties", time: 100 },
                { word: "get", time: 400 },
                { word: "to", time: 100 },
                { word: "yes", time: 100 },
                { word: "NEWLINE", time: 250 },
                { word: "the", time: 250 },
                { word: "pieces", time: 250 },
                { word: "that", time: 250 },
                { word: "are", time: 250 },
                { word: "sacrifised", time: 100 },
                { word: "in", time: 400 },
            ],
            afterLyrics: "in every game of chess",
            extendedLyrics: [
                { word: "we", time: 1200 },
                { word: "just", time: 200 },
                { word: "assume", time: 800 },
                { word: "that", time: 100 },
                { word: "it", time: 200 },
                { word: "happens", time: 100 },
            ]
        },
        {
            songName: "My Shot",
            albumCover: "https://upload.wikimedia.org/wikipedia/en/5/5b/Hamilton_cast_recording_cover.jpeg",
            artist: "Lin-Manuel Miranda",
            beforeMp3path: "/myshotbefore.mp3",
            afterMp3path: "/myshotafter.mp3",
            beforeLyrics: [
                { word: "i'm", time: 0 },
                { word: "laughin", time: 50 },
                { word: "in", time: 200 },
                { word: "the", time: 200 },
                { word: "face", time: 200 },
                { word: "of", time: 200 },
                { word: "casualties", time: 200 },
                { word: "and", time: 200 },
                { word: "sorrow", time: 300 },
                { word: "NEWLINE", time: 100 },
                { word: "for", time: 200 },
                { word: "the", time: 200 },
                { word: "first", time: 200 },
                { word: "time", time: 200 },
                { word: "i'm", time: 300 },
            ],
            afterLyrics: "thinking past tommorrow",
            extendedLyrics: [
                { word: "and", time: 1200 },
                { word: "i", time: 250 },
                { word: "am", time: 250 },
                { word: "not", time: 250 },
                { word: "blowing", time: 400 },
                { word: "away", time: 400 },
                { word: "my", time: 350 },
                { word: "shot", time: 500 },
            ]
        },
        {
            songName: "Runaway",
            albumCover: "https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f",
            artist: "Kanye West, Pusha T",
            beforeMp3path: "/runawaybefore.mp3",
            afterMp3path: "/runawayafter.mp3",
            beforeLyrics: [
                { word: "and", time: 2350 },
                { word: "i", time: 50 },
                { word: "always", time: 50 },
                { word: "find", time: 800 },
                { word: "yeah", time: 200 },
                { word: "i", time: 200 },
                { word: "always", time: 200 },
                { word: "find", time: 800 },
                { word: "something", time: 200 },
                { word: "wrong", time: 600 },
                { word: "NEWLINE", time: 1000 },
                { word: "you've", time: 1000 },
                { word: "been", time: 200 },
                { word: "putting", time: 200 },
                { word: "up", time: 300 },
                { word: "with", time: 200 },
                { word: "my", time: 350 },
                { word: "sh*t", time: 200 },
            ],
            afterLyrics: "just way too long",
            extendedLyrics: [
                { word: "i'm", time: 3500 },
                { word: "so", time: 250 },
                { word: "gifted", time: 250 },
                { word: "at", time: 400 },
                { word: "find-ing", time: 700 },
                { word: "what", time: 350 },
                { word: "i", time: 200 },
                { word: "don't", time: 200 },
                { word: "like", time: 200 },
                { word: "the", time: 350 },
                { word: "most", time: 480 },
            ]
        }
    ]